/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBaseV1Core, IBaseV1CoreInterface } from "../IBaseV1Core";

const _abi = [
  {
    inputs: [],
    name: "claimFees",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "tokens",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBaseV1Core__factory {
  static readonly abi = _abi;
  static createInterface(): IBaseV1CoreInterface {
    return new utils.Interface(_abi) as IBaseV1CoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBaseV1Core {
    return new Contract(address, _abi, signerOrProvider) as IBaseV1Core;
  }
}
