/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBribeFactory, IBribeFactoryInterface } from "../IBribeFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_allowedRewardTokens",
        type: "address[]",
      },
    ],
    name: "createBribe",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBribeFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IBribeFactoryInterface {
    return new utils.Interface(_abi) as IBribeFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBribeFactory {
    return new Contract(address, _abi, signerOrProvider) as IBribeFactory;
  }
}
