/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { VeDist, VeDistInterface } from "../VeDist";

const _abi = [
  {
    inputs: [],
    name: "checkpoint_token",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "checkpoint_total_supply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class VeDist__factory {
  static readonly abi = _abi;
  static createInterface(): VeDistInterface {
    return new utils.Interface(_abi) as VeDistInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): VeDist {
    return new Contract(address, _abi, signerOrProvider) as VeDist;
  }
}
