/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface BaseV1BribeFactoryUpgradeableInterface
  extends ethers.utils.Interface {
  functions: {
    "createBribe()": FunctionFragment;
    "last_gauge()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createBribe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "last_gauge",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createBribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "last_gauge", data: BytesLike): Result;

  events: {};
}

export class BaseV1BribeFactoryUpgradeable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BaseV1BribeFactoryUpgradeableInterface;

  functions: {
    createBribe(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    last_gauge(overrides?: CallOverrides): Promise<[string]>;
  };

  createBribe(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  last_gauge(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createBribe(overrides?: CallOverrides): Promise<string>;

    last_gauge(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createBribe(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    last_gauge(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createBribe(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    last_gauge(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
