/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SolidlyLibraryInterface extends ethers.utils.Interface {
  functions: {
    "getAmountOut(uint256,address,address,bool)": FunctionFragment;
    "getMinimumValue(address,address,bool)": FunctionFragment;
    "getSample(address,address,bool)": FunctionFragment;
    "getTradeDiff(uint256,address,address,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [BigNumberish, string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumValue",
    values: [string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getSample",
    values: [string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeDiff",
    values: [BigNumberish, string, string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSample", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTradeDiff",
    data: BytesLike
  ): Result;

  events: {};
}

export class SolidlyLibrary extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SolidlyLibraryInterface;

  functions: {
    getAmountOut(
      amountIn: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMinimumValue(
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    getSample(
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getTradeDiff(uint256,address,address,bool)"(
      amountIn: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { a: BigNumber; b: BigNumber }>;

    "getTradeDiff(uint256,address,address)"(
      amountIn: BigNumberish,
      tokenIn: string,
      pair: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { a: BigNumber; b: BigNumber }>;
  };

  getAmountOut(
    amountIn: BigNumberish,
    tokenIn: string,
    tokenOut: string,
    stable: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMinimumValue(
    tokenIn: string,
    tokenOut: string,
    stable: boolean,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>;

  getSample(
    tokenIn: string,
    tokenOut: string,
    stable: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getTradeDiff(uint256,address,address,bool)"(
    amountIn: BigNumberish,
    tokenIn: string,
    tokenOut: string,
    stable: boolean,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { a: BigNumber; b: BigNumber }>;

  "getTradeDiff(uint256,address,address)"(
    amountIn: BigNumberish,
    tokenIn: string,
    pair: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { a: BigNumber; b: BigNumber }>;

  callStatic: {
    getAmountOut(
      amountIn: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinimumValue(
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    getSample(
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTradeDiff(uint256,address,address,bool)"(
      amountIn: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { a: BigNumber; b: BigNumber }>;

    "getTradeDiff(uint256,address,address)"(
      amountIn: BigNumberish,
      tokenIn: string,
      pair: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { a: BigNumber; b: BigNumber }>;
  };

  filters: {};

  estimateGas: {
    getAmountOut(
      amountIn: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinimumValue(
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSample(
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTradeDiff(uint256,address,address,bool)"(
      amountIn: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTradeDiff(uint256,address,address)"(
      amountIn: BigNumberish,
      tokenIn: string,
      pair: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAmountOut(
      amountIn: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinimumValue(
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSample(
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTradeDiff(uint256,address,address,bool)"(
      amountIn: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      stable: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTradeDiff(uint256,address,address)"(
      amountIn: BigNumberish,
      tokenIn: string,
      pair: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
